### PR TITLE
News: add links to published Talk and Workshop YouTube playlist

### PR DESCRIPTION
**Pull request by practicalli-john**
Create a news item for:
- playlist of all talks
- playlist for SciCloj workshops

#### Screenshot of locally running website

reclojure-news-youtube-links

### CODE REVIEW

**Comment by daslu** [comment]
Hi @practicalli-john, nice!

Note there are two distinct playlists: for the workshops and for the data science special.
In this PR, it looked like they were mixed up.

workshops:
https://www.youtube.com/watch?v=OIhLXQ1fdZs&list=PLtw0bWXdq7pOzX2T7eeHq_nnGDQkjsdR5

data science special:

https://www.youtube.com/watch?v=t32bIbzQdCU&list=PLtw0bWXdq7pNyb2NojSGBnCARRuvLxsAc

**Comment by practicalli-john** [comment]
Oh, I didn't spot there were two separate play list.  I'll create another PR and add a new news item for the Scicloj special and fix the wording of the workshops link
Thanks.

**Comment by daslu** [comment]
Thanks!

**Comment by practicalli-john** [comment]
Updated the news with a separate workshop video link and corrected the SciCloj name in #92

**Pull request merged**
