### PR TITLE
Add speakers section

### PR DESCRIPTION
**Pull request by barrosfelipe**
Also:

- Simplify main header and add News section
- Add individual speaker pages (WIP)

The speakers section and pages data is coming from a `db` namespace, but the news are hardcoded hiccup for now.

## Header with News
Screen Shot 2021-10-09 at 12 31 04

## Speakers section
Screen Shot 2021-10-09 at 12 31 11

## Speaker page
Screen Shot 2021-10-09 at 12 31 27

### CODE REVIEW

**Comment by reborg** [comment]
Hey @barrosfelipe overall nice and clean design, not a lot to say for me on that. I see that you have abandoned many of the ideas from the current version, waves and stickers, going for a design similar to the the mobile page. It's okay here, wondering what changed your mind. 

* Minor: picture of Gerald slightly overlapping the text of his name below. Some more padding?
* Sponsors disappeared except Gaiwan.
* Future: I guess you thought what happens when there are more news, is the box going to scroll?

**Comment by barrosfelipe** [comment]
> ...wondering what changed your mind.

Mostly to be pragmatic and speed up this iterative design process. It's very expensive (time wise) to design with code, change stuff organically and still have it looking good, so I felt like going for a cleaner and safer design. At least until we really have most of the picture painted, and then if it makes sense we can embellish a bit more. The background and the sticker effect can be toggled back quite easily as well.

As I ended up choosing to go more _squarey_ with the Sussman element, it also clashed a bit with what I had for the home before (curvy sticker effect and waves). I want the website to look great, but I'm already two months in and there are still things to add and at least two or three iterations, so I felt like I should decrease the complexity.

> Minor: picture of Gerald slightly overlapping the text of his name below. Some more padding?

Can you send a screenshot?

> Freshcode disappeared from the sponsors, as well as "re:Clojure is a free, community-driven conference" from the opening description. I guess it's just missing merge from master.

Not sure I get it. Freshcode was not there before if I recall correctly, but the opening should definitely be there. Can you send screenshots for this as well?

> Can you please add another confirmed speaker: Alexander Oloo

Sure!

> Future: I guess you thought what happens when there are more news, is the box going to scroll?

Yeah, it already does if you clone the elements.

**Comment by barrosfelipe** [comment]
Alright, I have fixed the conflicts. Please be aware that I have force pushed the changes.

- [ ] Picture of Gerald
- [x] Freshcode logo
- [x] Add Alexander Oloo
- [x] Conflicts with master branch

The Gerald picture is hopefully fixed as I can't reproduce it here after all the changes. Please let me know.

Also, should I already remove the CFP CTA?

An issue to notice is that shadow-cljs is probably being deployed in a wrong manner as I'm getting some weird warnings here. I'll check that with the team tomorrow as I want to add a little bit of optional JS to improve the navigation. Actually, I think it's time to move to Github Actions for deployment. See if I can get that going as well.

**Comment by reborg** [comment]
> The Gerald picture is hopefully fixed as I can't reproduce it here after all the changes. Please let me know.

That is really not a big deal. No problems.
 
> Also, should I already remove the CFP CTA?

Yes please.

> An issue to notice is that shadow-cljs is probably being deployed in a wrong manner as I'm getting some weird warnings here. I'll check that with the team tomorrow as I want to add a little bit of optional JS to improve the navigation. Actually, I think it's time to move to Github Actions for deployment. See if I can get that going as well.

Ok, but could just be in separate PR (if any changes required). Here's it's working ok (after static generation).

Thanks!

**Pull request merged**
