### PR TITLE
Schedule update: Sami Yehonathan swap

### PR DESCRIPTION
**Pull request by dotemacs**
Slight update to the schedule

### CODE REVIEW

**Comment by qazwsxpawel** [comment]
issue

doesn't look right?

**Comment by reborg** [comment]
Also @dotemacs could you please add Daniel Slutsky https://twitter.com/daslu_?lang=en to the QA with Sami.

**Comment by dotemacs** [comment]
> issue
> 
> doesn't look right?

My bad, fixing...

**Comment by dotemacs** [comment]
@qazwsxpawel 

See now:

image

**Comment by dotemacs** [comment]
@reborg 

> Also @dotemacs could you please add Daniel Slutsky https://twitter.com/daslu_?lang=en to the QA with Sami.

image

**Comment by reborg** [comment]
@dotemacs it should be good to go! Have a double check, thanks.

**Pull request merged**
