### PR TITLE
2021 Redesign, first stage: Header + CFP

### PR DESCRIPTION
**Pull request by barrosfelipe**
Here it goes, the first part of the website, containing the header and the CFP CTA. I have already included the link to the CFP and the contact email. So, if everyone approves it, this version can go live.

I have also updated the readme with instructions on how to build and deploy this version.

GitHub Pages setup will probably need to be updated to serve the contents of the `/_site` directory instead of `/`.

Screenshot_20210901_225643

Sorry for the delay and I hope everyone enjoys it. 🎉

### CODE REVIEW

**Comment by reborg** [comment]
> Awesome work @barrosfelipe 🎉
> 
> But it looks like we've actually gotten rid of the `/2019` and `/2020-speakers` so merging this would break existing links.
> 
> We should add these 2 folders and their dependencies into our build process!

Agree, not urgent and perhaps we could go live with the Cfp, but it would be nice to have a way to archive the old website and link it to the "past editions". We did this in the past that's the reason of the /2019 subfolder. For /2020 I think we didn't do that, but we can always recover the last relevant commit and bring it under /2020.

**Comment by barrosfelipe** [comment]
Screen Shot 2021-09-10 at 05 33 28
Screen Shot 2021-09-10 at 05 33 26
Screen Shot 2021-09-10 at 05 33 22

**Comment by barrosfelipe** [comment]
A new keynote section, a new sponsor section, an improved logo, fixed some accessibility and performance issues, added the files for previous years. Hope it is working :) I'll be available tomorrow from 8am CMT -3 if something needs fixing.

**Review by reborg — APPROVED** [review]
Going to merge for publish, thanks @barrosfelipe

**Pull request merged**
